"""Build every LaTeX table and figure generated by the analysis package.

Equivalent to running the executable notebooks end to end, but as a plain
Python command.

Uso:
    python scripts/build_tex_artifacts.py --all
    python scripts/build_tex_artifacts.py --eda
    python scripts/build_tex_artifacts.py --models
    python scripts/build_tex_artifacts.py --evaluation
    python scripts/build_tex_artifacts.py --benchmarks
    python scripts/build_tex_artifacts.py --generalizacao

Le o cache de previsoes (data/forecasts/, produzido por run_pipeline.py) e
regenera as tabelas e figuras em tcc-latex/{tables,figures}/generated/.
Each module owns its `run_all` function; this script only orchestrates them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Callable

from forecasting import benchmarks, eda, evaluation, models
from forecasting.config import load_config


def _step(label: str, fn: Callable, cfg) -> int:
    print(f"\n=== {label} ===")
    try:
        artifacts = fn(cfg)
        for path in artifacts or []:
            print(f"  + {path}")
        return 0
    except Exception as e:
        print(f"  ! ERROR: {type(e).__name__}: {e}")
        return 2


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true",
                        help="Executar todas as etapas em ordem.")
    parser.add_argument("--eda", action="store_true",
                        help="Estatisticas descritivas, decomposicao, ACF/PACF.")
    parser.add_argument("--models", action="store_true",
                        help="Model reports and forecast diagnostics.")
    parser.add_argument("--evaluation", action="store_true",
                        help="Metricas, rankings and skill scores.")
    parser.add_argument("--benchmarks", action="store_true",
                        help="Benchmarks against official forecasts and Oliveira (2024).")
    parser.add_argument("--generalizacao", action="store_true",
                        help="Generalization run for larger Bahia municipalities.")
    parser.add_argument("--config", type=Path, default=None,
                        help="Path para .tcc-pipeline.json (default: busca na hierarquia).")
    args = parser.parse_args()

    cfg = load_config(args.config)
    print(f"Pipeline config carregado de manuscript root: {cfg.tcc_root}")
    print(f"  Tabelas em : {cfg.tables_dir_abs}")
    print(f"  Figuras em : {cfg.figures_dir_abs}")

    failures = 0
    if args.all or args.eda:
        failures += _step("EDA", eda.run_all, cfg)
    if args.all or args.models:
        failures += _step("Modelos", models.run_all, cfg)
    if args.all or args.evaluation:
        failures += _step("Avaliacao", evaluation.run_all, cfg)
    if args.all or args.benchmarks:
        failures += _step("Benchmarks", benchmarks.run_all, cfg)
    if args.all or args.generalizacao:
        from forecasting import generalization
        failures += _step("Generalizacao", generalization.run_all, cfg)

    if not any([args.all, args.eda, args.models, args.evaluation,
                args.benchmarks, args.generalizacao]):
        parser.print_help()
        return 1

    print(f"\nConcluido. {failures} passo(s) com erro/stub.")
    return 0 if failures == 0 else 3


if __name__ == "__main__":
    sys.exit(main())
